"""Inline BYOS subprocess runner — generated, do not edit by hand.

Source of truth: ``osimflow.byos_contract._BYOS_CONTRACT`` (issue #1061).
Regenerate via ``python tools/_generate_byos_runner.py`` or
``make contract``.

This module exists because the inline subprocess runner is executed
with ``subprocess.Popen(['python', '-c', _SUBPROCESS_RUNNER, ...])`` in
a sanitised child Python interpreter.  Keeping the runner self-contained
(no imports from ``osimflow``) preserves the isolation guarantee
(issue #764) and means the subprocess validation cannot drift if the
parent ``osimflow`` package is unavailable.

The contract table is embedded into the inline runner script as a
literal copy — both the outer ``_BYOS_CONTRACT_SNAPSHOT`` constant and
the in-subprocess ``_INLINE_BYOS_CONTRACT`` dict are regenerated from
``osimflow.byos_contract._BYOS_CONTRACT`` on every regeneration, so they
cannot drift apart.  Adding a new entry to ``byos_contract`` without
re-running the generator will fail the drift tests in
``tests/unit/test_byos.py``.
"""

from __future__ import annotations

# Snapshot of osimflow.byos_contract._BYOS_CONTRACT at generation time.
# Regenerate via tools/_generate_byos_runner.py.
_BYOS_CONTRACT_SNAPSHOT: dict[str, dict[str, object]] = {'apply': {'accepts_kwargs': False,
           'param_names': ('template', 'parameters', 'sample_id', 'out'),
           'required_positional': 4},
 'apply_parameters': {'accepts_kwargs': False,
                      'param_names': ('template', 'parameters', 'sample_id', 'out'),
                      'required_positional': 4},
 'extract_kpis': {'accepts_kwargs': True,
                  'param_names': ('simulation_dir', 'sample_id', 'out'),
                  'required_positional': 3}}


_SUBPROCESS_RUNNER = """
import importlib.util
import inspect
import json
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")


# Inline copy of osimflow.byos_contract._BYOS_CONTRACT for subprocess
# validation (issue #1061).  Generated by tools/_generate_byos_runner.py
# — do NOT edit by hand.  Both this dict and ``_BYOS_CONTRACT_SNAPSHOT``
# are derived from the same source-of-truth table, so they cannot drift.
_INLINE_BYOS_CONTRACT = {'apply': {'accepts_kwargs': False,
           'param_names': ('template', 'parameters', 'sample_id', 'out'),
           'required_positional': 4},
 'apply_parameters': {'accepts_kwargs': False,
                      'param_names': ('template', 'parameters', 'sample_id', 'out'),
                      'required_positional': 4},
 'extract_kpis': {'accepts_kwargs': True,
                  'param_names': ('simulation_dir', 'sample_id', 'out'),
                  'required_positional': 3}}


class _InlineByosContractError(Exception):
    pass


def _inline_validate(fn, function_name):
    spec = _INLINE_BYOS_CONTRACT.get(function_name)
    if spec is None:
        return
    expected_count = spec["required_positional"]
    expected_names = spec["param_names"]
    sig = inspect.signature(fn)
    required = [
        p
        for p in sig.parameters.values()
        if p.default is inspect.Parameter.empty
        and p.kind in (
            inspect.Parameter.POSITIONAL_ONLY,
            inspect.Parameter.POSITIONAL_OR_KEYWORD,
        )
    ]
    if len(required) != expected_count:
        actual = f"{len(required)} required positional"
        expected = f"{expected_count} required positional"
        expected_list = ", ".join(expected_names)
        raise _InlineByosContractError(
            f"BYOS function '{function_name}' has {actual} parameter(s); "
            f"expected {expected} ({expected_list}). "
            f"Got signature: {sig}."
        )


def main():
    args_file = sys.argv[1]
    with open(args_file) as f:
        payload = json.load(f)

    script_path = payload["script"]
    function_name = payload["function"]
    positional_args = payload.get("args", [])
    keyword_args = payload.get("kwargs", {})

    # Deserialize Path arguments back from strings.
    # The BYOS contract specifies:
    #   apply_parameters(template: Path, parameters: dict, sample_id: str, out: Path) -> Path
    #   extract_kpis(simulation_dir: Path, sample_id: str, out: Path, **kwargs) -> Path
    #     (accepts optional keyword args such as openstudio_version: str | None)
    # So positions 0 and -1 (or 3 for apply_parameters) are Path-like.
    deserialized = []
    for i, arg in enumerate(positional_args):
        if isinstance(arg, str) and (
            i == 0  # first arg is always a Path (template or simulation_dir)
            or i == len(positional_args) - 1  # last arg is always 'out' Path
            or (function_name == "apply_parameters" and i == 3)  # 'out' is at index 3
        ):
            deserialized.append(Path(arg))
        elif isinstance(arg, dict):
            deserialized.append(arg)
        else:
            deserialized.append(arg)

    # Deserialize kwargs: Path-like values for known Path keys.
    path_keys = {"template", "out", "simulation_dir", "modified_sim_package"}
    deserialized_kwargs = {}
    for k, v in keyword_args.items():
        if k in path_keys and isinstance(v, str):
            deserialized_kwargs[k] = Path(v)
        else:
            deserialized_kwargs[k] = v

    # Load the user script module.
    spec = importlib.util.spec_from_file_location("_byos_module", script_path)
    if spec is None or spec.loader is None:
        print(json.dumps({"error": f"could not load spec for {script_path}"}))
        sys.exit(1)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    fn = getattr(mod, function_name, None)
    if fn is None or not callable(fn):
        print(json.dumps({"error": f"function {function_name!r} not found in {script_path}"}))
        sys.exit(1)

    # Validate the signature against the documented BYOS contract
    # (issue #1048). Raises ``_InlineByosContractError`` on arity mismatch.
    try:
        _inline_validate(fn, function_name)
    except _InlineByosContractError as exc:
        print(json.dumps({"error": str(exc), "type": "ByosContractError"}))
        sys.exit(1)

    try:
        result = fn(*deserialized, **deserialized_kwargs)
        # The BYOS contract always returns a Path.
        print(json.dumps({"result": str(result)}))
    except Exception as exc:
        print(json.dumps({"error": f"{type(exc).__name__}: {exc}"}))
        sys.exit(1)

main()
"""
