"""End-to-end integration test against the REAL OpenStudio CLI.

This test runs INSIDE the ``nrel/openstudio:<version>`` container in CI
(via ``.github/workflows/openstudio-e2e.yml``). It generates a valid
``.osm`` seed model using the OpenStudio Ruby bindings, writes a
minimal ``workflow.osw``, and then runs a Campaign end-to-end so that
``openstudio.cli run -w workflow.osw`` is invoked for real.

The test is skipped unless:
  - ``openstudio.cli`` is on PATH (we are inside the container), AND
  - ``OSIMFLOW_RUN_REAL_OPENSTUDIO=1`` is set in the environment.

Strategy: the template package contains TWO model files:

  - ``model.osm`` — JSON-mode convention (``{"attributes": {...}}``)
    used by the parameter-application step for attribute mapping.
  - ``real_model.osm`` — a real OpenStudio model generated by the
    Ruby bindings, referenced as the seed file in ``workflow.osw``.

A BYOS apply script copies the entire template directory (including
both files) into each sample's output directory.  The simulation step
then invokes ``openstudio.cli run -w workflow.osw`` against the real
model.

Acceptance criteria (issue #162):

  - The campaign completes without error for all 3 samples.
  - ``eplusout.sql`` is produced (real EnergyPlus output).
  - ``eplusout.err`` exists and contains no Severe errors.
  - ``run.json`` records ``n_succeeded == 3`` and ``n_failed == 0``.
  - All four standard output artifacts are produced.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

from osimflow import Campaign, CampaignConfig
from osimflow.executors import LocalExecutor
from osimflow.work import _is_openstudio_available

REPO_ROOT = Path(__file__).resolve().parents[2]
EXAMPLE_VARS_YML = REPO_ROOT / "variables.yml"
SCRIPTS_DIR = REPO_ROOT / "osimflow" / "_scripts"


def _real_cli_enabled() -> bool:
    return (
        _is_openstudio_available()
        and os.environ.get("OSIMFLOW_RUN_REAL_OPENSTUDIO") == "1"
    )


skip_unless_real_cli = pytest.mark.skipif(
    not _real_cli_enabled(),
    reason="Real OpenStudio CLI not available or OSIMFLOW_RUN_REAL_OPENSTUDIO != 1",
)


def _generate_real_model(output_path: Path) -> None:
    subprocess.run(
        ["ruby", str(SCRIPTS_DIR / "generate_seed_model.rb"), str(output_path)],
        check=True,
        capture_output=True,
        text=True,
    )


def _write_byos_apply_script(path: Path) -> None:
    path.write_text(
        """\
import json
from pathlib import Path

def apply_parameters(template: Path, parameters: dict, sample_id: str, out: Path) -> Path:
    out_dir = out / sample_id
    out_dir.mkdir(parents=True, exist_ok=True)
    for child in template.iterdir():
        if child.is_file():
            import shutil as _sh
            _sh.copy2(child, out_dir / child.name)
    # Also mutate the JSON-mode model.osm so the pre-flight attribute
    # check is consistent with the parameter values.
    json_osm = out_dir / "model.osm"
    if json_osm.exists():
        text = json_osm.read_text()
        if text.lstrip().startswith("{"):
            data = json.loads(text)
            for name, value in parameters.items():
                data.setdefault("attributes", {})[name] = value
            json_osm.write_text(json.dumps(data, indent=2, sort_keys=True))
    return out_dir
"""
    )


@pytest.fixture
def real_example_pkg(tmp_path: Path) -> Path:
    pkg = tmp_path / "real_example_package"
    pkg.mkdir()

    _generate_real_model(pkg / "real_model.osm")

    # JSON-mode model.osm for parameter mapping.
    (pkg / "model.osm").write_text(json.dumps({
        "attributes": {
            "window_u_value": 3.0,
            "infiltration_rate": 0.7,
            "hvac_setpoint": 22.0,
            "lighting_power_density": 10.0,
            "thermal_conductivity": 0.5,
            "internal_gain": 5.0,
            "equipment_lifetime": 15.0,
        },
        "metadata": {
            "building_type": "Office",
            "model_format": "test-mode JSON for parameter mapping",
        },
    }, indent=2))

    epw_env = os.environ.get("OSIMFLOW_E2E_EPW_PATH", "")
    weather_file = ""
    if epw_env and Path(epw_env).exists():
        shutil.copy2(epw_env, pkg / "weather.epw")
        weather_file = "weather.epw"

    osw = {
        "seed_file": "real_model.osm",
        "weather_file": weather_file,
        "measure_paths": [],
        "steps": [],
    }
    (pkg / "workflow.osw").write_text(json.dumps(osw, indent=2))

    return pkg


@pytest.fixture
def real_workdir(tmp_path: Path) -> Path:
    wd = tmp_path / "work"
    wd.mkdir()
    (wd / "variables.yml").write_text(EXAMPLE_VARS_YML.read_text())
    return wd


@pytest.fixture
def real_outdir(real_workdir: Path) -> Path:
    od = real_workdir / "out"
    od.mkdir()
    return od


@pytest.fixture
def real_byos(real_workdir: Path) -> Path:
    script = real_workdir / "byos_apply.py"
    _write_byos_apply_script(script)
    return script


@pytest.fixture
def real_cfg(
    real_workdir: Path,
    real_example_pkg: Path,
    real_outdir: Path,
    real_byos: Path,
) -> CampaignConfig:
    return CampaignConfig(
        input_variables=real_workdir / "variables.yml",
        template_sim_package=real_example_pkg,
        n_samples=3,
        outdir=real_outdir,
        openstudio_version="3.9.0",
        archive_intermediates=False,
        custom_apply_script=real_byos,
    )


@skip_unless_real_cli
def test_real_openstudio_cli_three_sample_campaign(
    real_cfg: CampaignConfig,
    real_outdir: Path,
) -> None:
    result = Campaign(cfg=real_cfg, executor=LocalExecutor(max_workers=1)).run()

    run_json = real_outdir / "run.json"
    assert run_json.is_file(), f"missing run.json: {run_json}"
    trace = json.loads(run_json.read_text())
    assert trace["summary"]["n_samples"] == 3
    assert trace["summary"]["n_succeeded"] == 3
    assert trace["summary"]["n_failed"] == 0

    for row in trace["per_sample"]:
        assert row["status"] == "ok", f"sample {row['sample_id']} failed"

    csv_path = real_outdir / "aggregated_results.csv"
    assert csv_path.is_file()
    assert len(csv_path.read_text().strip().splitlines()) == 4  # header + 3

    assert (real_outdir / "failed_simulations.csv").is_file()

    kpi_files = list((real_outdir / "work" / "kpis").glob("kpi_*.json"))
    assert len(kpi_files) == 3

    sim_dir = real_outdir / "work" / "sim"
    for sample_dir in sim_dir.iterdir():
        if not sample_dir.is_dir():
            continue
        sql = sample_dir / "eplusout.sql"
        assert sql.exists(), f"missing eplusout.sql in {sample_dir}"

        err_file = sample_dir / "eplusout.err"
        if err_file.exists():
            err_text = err_file.read_text(errors="replace")
            severe = [line for line in err_text.splitlines() if "Severe" in line]
            assert not severe, (
                f"Severe EnergyPlus errors in {sample_dir}:\n"
                + "\n".join(severe[:5])
            )

    assert (real_outdir / "plots").is_dir()
    assert set(result) >= {"samples", "kpis", "aggregated", "plots", "elapsed_s", "run_json"}
    assert result["elapsed_s"] > 0.0
