#!/usr/bin/env python3
"""Generate the inline BYOS subprocess runner with the contract table baked in.

Issue #1061: ``osimflow.byos._BYOS_CONTRACT`` and the inline subprocess
runner in ``osimflow.byos._SUBPROCESS_RUNNER`` previously held a literal
copy of the same contract table.  This script ensures a single source of
truth: ``osimflow.byos_contract._BYOS_CONTRACT``.  The inline runner is
generated into ``osimflow/_byos_runner_generated.py`` with a snapshot of
the contract baked in, so the subprocess never has to import
``osimflow`` at runtime.

Run locally::

    python tools/_generate_byos_runner.py

…or via ``make contract`` / pre-commit.  Exit code 0 means the generated
file is already up to date; exit code 1 means the file was rewritten —
review the diff and commit it alongside the contract change.

Why generate instead of ``importlib.resources`` / runtime import?
    The inline runner is executed in a sanitised child Python process
    via ``subprocess.Popen(['python', '-c', _SUBPROCESS_RUNNER, ...])``.
    Keeping it self-contained (no external imports) preserves the
    isolation guarantee (issue #764) and means the subprocess
    validation cannot drift even if the parent ``osimflow`` package is
    unavailable on ``sys.path``.
"""

from __future__ import annotations

import importlib
import pprint
import sys
from pathlib import Path
from typing import TYPE_CHECKING

# Ensure the ``osimflow`` package is importable regardless of the
# current working directory (the script is intended to be runnable from
# anywhere, including via ``make contract`` from the repo root).
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


if TYPE_CHECKING:
    from collections.abc import Mapping


OUTPUT_PATH = REPO_ROOT / "osimflow" / "_byos_runner_generated.py"


# Template for the inline runner. ``{CONTRACT_LITERAL}`` is replaced at
# generation time with a Python literal representing the contract table.
# Everything else is written verbatim — the outer template is a regular
# ``str`` (no f-string interpretation), so the subprocess f-strings
# below appear with single braces in the generated file.
#
# The contract literal appears twice in the generated output: once at
# the outer module level (``_BYOS_CONTRACT_SNAPSHOT``) and once inside
# the inline subprocess runner.  The inline copy is needed because the
# subprocess is a fresh Python interpreter with no access to the outer
# module's globals — but both copies come from the same generator, so
# they cannot drift apart (issue #1061).
_RUNNER_TEMPLATE = '''"""Inline BYOS subprocess runner — generated, do not edit by hand.

Source of truth: ``osimflow.byos_contract._BYOS_CONTRACT`` (issue #1061).
Regenerate via ``python tools/_generate_byos_runner.py`` or
``make contract``.

This module exists because the inline subprocess runner is executed
with ``subprocess.Popen(['python', '-c', _SUBPROCESS_RUNNER, ...])`` in
a sanitised child Python interpreter.  Keeping the runner self-contained
(no imports from ``osimflow``) preserves the isolation guarantee
(issue #764) and means the subprocess validation cannot drift if the
parent ``osimflow`` package is unavailable.

The contract table is embedded into the inline runner script as a
literal copy — both the outer ``_BYOS_CONTRACT_SNAPSHOT`` constant and
the in-subprocess ``_INLINE_BYOS_CONTRACT`` dict are regenerated from
``osimflow.byos_contract._BYOS_CONTRACT`` on every regeneration, so they
cannot drift apart.  Adding a new entry to ``byos_contract`` without
re-running the generator will fail the drift tests in
``tests/unit/test_byos.py``.
"""

from __future__ import annotations

# Snapshot of osimflow.byos_contract._BYOS_CONTRACT at generation time.
# Regenerate via tools/_generate_byos_runner.py.
_BYOS_CONTRACT_SNAPSHOT: dict[str, dict[str, object]] = {CONTRACT_LITERAL}


_SUBPROCESS_RUNNER = """
import importlib.util
import inspect
import json
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")


# Inline copy of osimflow.byos_contract._BYOS_CONTRACT for subprocess
# validation (issue #1061).  Generated by tools/_generate_byos_runner.py
# — do NOT edit by hand.  Both this dict and ``_BYOS_CONTRACT_SNAPSHOT``
# are derived from the same source-of-truth table, so they cannot drift.
_INLINE_BYOS_CONTRACT = {CONTRACT_LITERAL}


class _InlineByosContractError(Exception):
    pass


def _inline_validate(fn, function_name):
    spec = _INLINE_BYOS_CONTRACT.get(function_name)
    if spec is None:
        return
    expected_count = spec["required_positional"]
    expected_names = spec["param_names"]
    sig = inspect.signature(fn)
    required = [
        p
        for p in sig.parameters.values()
        if p.default is inspect.Parameter.empty
        and p.kind in (
            inspect.Parameter.POSITIONAL_ONLY,
            inspect.Parameter.POSITIONAL_OR_KEYWORD,
        )
    ]
    if len(required) != expected_count:
        actual = f"{len(required)} required positional"
        expected = f"{expected_count} required positional"
        expected_list = ", ".join(expected_names)
        raise _InlineByosContractError(
            f"BYOS function '{function_name}' has {actual} parameter(s); "
            f"expected {expected} ({expected_list}). "
            f"Got signature: {sig}."
        )


def main():
    args_file = sys.argv[1]
    with open(args_file) as f:
        payload = json.load(f)

    script_path = payload["script"]
    function_name = payload["function"]
    positional_args = payload.get("args", [])
    keyword_args = payload.get("kwargs", {})

    # Deserialize Path arguments back from strings.
    # The BYOS contract specifies:
    #   apply_parameters(template: Path, parameters: dict, sample_id: str, out: Path) -> Path
    #   extract_kpis(simulation_dir: Path, sample_id: str, out: Path, **kwargs) -> Path
    #     (accepts optional keyword args such as openstudio_version: str | None)
    # So positions 0 and -1 (or 3 for apply_parameters) are Path-like.
    deserialized = []
    for i, arg in enumerate(positional_args):
        if isinstance(arg, str) and (
            i == 0  # first arg is always a Path (template or simulation_dir)
            or i == len(positional_args) - 1  # last arg is always 'out' Path
            or (function_name == "apply_parameters" and i == 3)  # 'out' is at index 3
        ):
            deserialized.append(Path(arg))
        elif isinstance(arg, dict):
            deserialized.append(arg)
        else:
            deserialized.append(arg)

    # Deserialize kwargs: Path-like values for known Path keys.
    path_keys = {"template", "out", "simulation_dir", "modified_sim_package"}
    deserialized_kwargs = {}
    for k, v in keyword_args.items():
        if k in path_keys and isinstance(v, str):
            deserialized_kwargs[k] = Path(v)
        else:
            deserialized_kwargs[k] = v

    # Load the user script module.
    spec = importlib.util.spec_from_file_location("_byos_module", script_path)
    if spec is None or spec.loader is None:
        print(json.dumps({"error": f"could not load spec for {script_path}"}))
        sys.exit(1)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    fn = getattr(mod, function_name, None)
    if fn is None or not callable(fn):
        print(json.dumps({"error": f"function {function_name!r} not found in {script_path}"}))
        sys.exit(1)

    # Validate the signature against the documented BYOS contract
    # (issue #1048). Raises ``_InlineByosContractError`` on arity mismatch.
    try:
        _inline_validate(fn, function_name)
    except _InlineByosContractError as exc:
        print(json.dumps({"error": str(exc), "type": "ByosContractError"}))
        sys.exit(1)

    try:
        result = fn(*deserialized, **deserialized_kwargs)
        # The BYOS contract always returns a Path.
        print(json.dumps({"result": str(result)}))
    except Exception as exc:
        print(json.dumps({"error": f"{type(exc).__name__}: {exc}"}))
        sys.exit(1)

main()
"""
'''


def _contract_as_plain_dict(contract: Mapping[str, object]) -> dict[str, dict[str, object]]:
    """Convert the contract entries to plain ``dict`` for ``pprint``.

    ``osimflow.byos_contract.ByosContractEntry`` is a ``NamedTuple``; the
    generated runner only needs the public data (the tuple values) and
    must embed it as a plain Python literal so the runner can ``exec``
    without depending on ``osimflow.byos_contract``.
    """
    plain: dict[str, dict[str, object]] = {}
    for name, entry in contract.items():
        # ``NamedTuple`` exposes ``_asdict`` which returns an
        # ``OrderedDict[str, Any]``; ``dict(...)`` copies it.  For
        # dataclasses / objects with ``__dict__`` we copy that instead.
        if hasattr(entry, "_asdict"):
            plain[name] = dict(entry._asdict())
        else:
            plain[name] = dict(vars(entry))
    return plain


def _render_contract_literal(contract: Mapping[str, object]) -> str:
    """Render the contract table as a stable Python literal string."""
    plain = _contract_as_plain_dict(contract)
    # ``sort_dicts=True`` (default) keeps the output deterministic across
    # Python versions; ``width=88`` matches ruff's default line length so
    # the generated file passes ``ruff format --check`` without
    # reformatting.
    return pprint.pformat(plain, width=88, sort_dicts=True)


def _build_output(contract_literal: str) -> str:
    """Substitute the contract literal into the runner template."""
    return _RUNNER_TEMPLATE.replace("{CONTRACT_LITERAL}", contract_literal)


def main() -> int:
    # Force reload so the script sees the current on-disk source even
    # when ``osimflow.byos_contract`` was imported earlier in this process.
    sys.modules.pop("osimflow.byos_contract", None)
    contract_mod = importlib.import_module("osimflow.byos_contract")
    contract = contract_mod._BYOS_CONTRACT

    contract_literal = _render_contract_literal(contract)
    output_text = _build_output(contract_literal)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if OUTPUT_PATH.exists() and OUTPUT_PATH.read_text() == output_text:
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)}: up to date")
        return 0

    OUTPUT_PATH.write_text(output_text)
    print(
        f"{OUTPUT_PATH.relative_to(REPO_ROOT)}: regenerated "
        f"(re-run `git diff` to review; commit alongside the contract change)"
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
