"""Tests for the SEC-001 serve auth behaviour (issue #1553).

The SEC-001 localhost gap was that ``osimflow serve --outdir ./results``
(``--enable-writes`` NOT set, no ``--api-key``, no ``--api-keys-file``)
ran fully unauthenticated on the loopback bind. On a shared HPC login
node every local account could read ``run.json`` / KPI results /
registry listings via ``http://127.0.0.1:8000``.

The fix (issue #1553): always auto-generate an API key when no key
store is configured. Reuses the existing ``#1117`` mechanism
(``osimflow.api.generate_api_key``), surfaces the key once on stderr
so the operator can capture it, and logs a WARNING describing the
multi-user-host exposure.

These tests mirror the ``TestAutoGeneratedApiKeyDisplay`` tests in
``tests/unit/test_api_tls.py`` for the ``--enable-writes`` path, but
also cover the read-only path (the actual bug) plus the failure path.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from osimflow.__main__ import _build_parser, _cmd_serve


def _patched_serve(monkeypatch, tmp_path: Path, args):
    """Run ``_cmd_serve`` with uvicorn and create_app patched.

    Returns a context-manager-style handle so the caller can assert on
    ``mock_create.call_args``. ``monkeypatch`` is required so the
    ``sys.modules`` patch is reverted after the test.
    """
    mock_app = MagicMock()
    mock_uvicorn = MagicMock()
    monkeypatch.setitem(sys.modules, "uvicorn", mock_uvicorn)
    return mock_app, mock_uvicorn


class TestServeAutoGenKeyProvided:
    """Mode 1 — user supplied ``--api-key``: no auto-gen, no notice, no WARNING."""

    def test_explicit_api_key_used_as_is(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """The user's --api-key is passed through verbatim to create_app."""
        parser = _build_parser()
        args = parser.parse_args(
            [
                "serve",
                "--outdir",
                str(tmp_path),
                "--api-key",
                "user-supplied-stable-key",
            ]
        )
        mock_app, mock_uvicorn = _patched_serve(monkeypatch, tmp_path, args)
        with patch("osimflow.api.create_app", return_value=mock_app) as mock_create:
            result = _cmd_serve(args)

        assert result == 0
        mock_create.assert_called_once()
        assert mock_create.call_args[1]["api_key"] == "user-supplied-stable-key"

        captured = capsys.readouterr()
        combined = captured.out + captured.err
        # No auto-gen banner when the user supplies a key.
        assert "Generated ephemeral API key" not in combined
        assert "won't be shown again" not in combined
        mock_uvicorn.run.assert_called_once_with(mock_app, host="127.0.0.1", port=8000)

    def test_explicit_api_key_no_sec001_warning(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture
    ) -> None:
        """The multi-user-host WARNING only fires on auto-gen, not when a key is supplied."""
        parser = _build_parser()
        args = parser.parse_args(
            [
                "serve",
                "--outdir",
                str(tmp_path),
                "--api-key",
                "user-supplied-stable-key",
            ]
        )
        mock_app, _ = _patched_serve(monkeypatch, tmp_path, args)
        with patch("osimflow.api.create_app", return_value=mock_app):
            with caplog.at_level(logging.WARNING, logger="osimflow.__main__"):
                _cmd_serve(args)

        sec001_msgs = [r for r in caplog.records if "SEC-001" in r.getMessage()]
        # User supplied --api-key: the auto-gen-only warning must NOT fire.
        assert sec001_msgs == []


class TestServeAutoGenReadOnly:
    """Mode 2 — read-only bind with no key: auto-gen closes the SEC-001 gap.

    This is the bug the issue fixes: previously the read-only serve ran
    fully unauthenticated on the loopback bind and every local account
    could read campaign data. The auto-gen must fire even when
    ``--enable-writes`` is NOT set.
    """

    def test_read_only_auto_generates_key(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """--enable-writes absent + no --api-key: create_app still receives a key."""
        parser = _build_parser()
        args = parser.parse_args(["serve", "--outdir", str(tmp_path)])
        mock_app, _ = _patched_serve(monkeypatch, tmp_path, args)
        with patch("osimflow.api.create_app", return_value=mock_app) as mock_create:
            result = _cmd_serve(args)

        assert result == 0
        assert mock_create.call_args is not None
        api_key = mock_create.call_args[1]["api_key"]
        # Auto-gen must have fired even though --enable-writes is off.
        assert api_key is not None
        # generate_api_key() returns a URL-safe token of ~43 chars.
        assert len(api_key) >= 32, f"unexpected short key: {api_key!r}"
        # And the served app must NOT be flagged as read-only-auth-disabled.
        assert mock_create.call_args[1]["read_only"] is True

    def test_read_only_key_printed_to_stderr(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """The auto-generated key reaches the operator via stderr (one-liner)."""
        parser = _build_parser()
        args = parser.parse_args(["serve", "--outdir", str(tmp_path)])
        mock_app, _ = _patched_serve(monkeypatch, tmp_path, args)
        with patch("osimflow.api.create_app", return_value=mock_app) as mock_create:
            _cmd_serve(args)

        captured = capsys.readouterr()
        api_key = mock_create.call_args[1]["api_key"]
        assert api_key in captured.err, "key must surface on stderr for capture"
        # The one-liner notice is the canonical format (issue #1553).
        assert "Generated ephemeral API key for localhost serve" in captured.err
        # Single-line: only one newline in the notice (the trailing \n from print()).
        notice_line = next(
            line
            for line in captured.err.splitlines()
            if "Generated ephemeral API key" in line
        )
        assert "\n" not in notice_line.rstrip("\n")
        assert "--api-key" in notice_line

    def test_read_only_warning_logged(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture
    ) -> None:
        """The startup WARNING describing local-user exposure must fire at WARNING level."""
        parser = _build_parser()
        args = parser.parse_args(["serve", "--outdir", str(tmp_path)])
        mock_app, _ = _patched_serve(monkeypatch, tmp_path, args)
        with patch("osimflow.api.create_app", return_value=mock_app):
            with caplog.at_level(logging.DEBUG, logger="osimflow.__main__"):
                _cmd_serve(args)

        sec001 = [r for r in caplog.records if "SEC-001" in r.getMessage()]
        assert len(sec001) >= 1, "expected at least one SEC-001 WARNING log record"
        # The auto-gen WARNING must be at WARNING (not DEBUG/INFO) so it surfaces
        # under the default INFO log_level.
        assert any(r.levelno == logging.WARNING for r in sec001)
        # The message must mention the multi-user-host exposure (the threat
        # the issue calls out) and reference the host:port.
        warning_msg = next(r for r in sec001 if r.levelno == logging.WARNING).getMessage()
        assert "multi-user" in warning_msg.lower() or "multi user" in warning_msg.lower()
        assert "127.0.0.1" in warning_msg
        assert "8000" in warning_msg
        assert "1553" in warning_msg


class TestServeAutoGenReadWrite:
    """Mode 2b — read-write bind with no key: auto-gen (existing behaviour preserved)."""

    def test_read_write_auto_generates_key(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """--enable-writes + no --api-key: still auto-gens (issue #1117 path)."""
        parser = _build_parser()
        args = parser.parse_args(["serve", "--outdir", str(tmp_path), "--enable-writes"])
        mock_app, _ = _patched_serve(monkeypatch, tmp_path, args)
        with patch("osimflow.api.create_app", return_value=mock_app) as mock_create:
            result = _cmd_serve(args)

        assert result == 0
        api_key = mock_create.call_args[1]["api_key"]
        assert api_key is not None and len(api_key) >= 32
        assert mock_create.call_args[1]["read_only"] is False


class TestServeKeysFileMode:
    """Mode 3 — multi-user mode via ``--api-keys-file``: no auto-gen, no notice."""

    def test_keys_file_skips_autogen(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """When --api-keys-file is set, create_app receives None as api_key and no banner prints."""
        keys_file = tmp_path / "api_keys.json"
        keys_file.write_text(
            '{"users": [{"key": "k", "user_id": "u", "role": "admin"}]}'
        )
        parser = _build_parser()
        args = parser.parse_args(
            [
                "serve",
                "--outdir",
                str(tmp_path),
                "--api-keys-file",
                str(keys_file),
            ]
        )
        mock_app, _ = _patched_serve(monkeypatch, tmp_path, args)
        with patch("osimflow.api.create_app", return_value=mock_app) as mock_create:
            result = _cmd_serve(args)

        assert result == 0
        # Multi-user mode: api_key is None, api_keys_file is forwarded.
        assert mock_create.call_args[1]["api_key"] is None
        assert mock_create.call_args[1]["api_keys_file"] == keys_file
        captured = capsys.readouterr()
        assert "Generated ephemeral API key" not in captured.err
        assert "Generated ephemeral API key" not in captured.out

    def test_keys_file_with_explicit_key_warns(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture
    ) -> None:
        """Passing --api-key alongside --api-keys-file still warns + ignores the key."""
        keys_file = tmp_path / "api_keys.json"
        keys_file.write_text(
            '{"users": [{"key": "k", "user_id": "u", "role": "admin"}]}'
        )
        parser = _build_parser()
        args = parser.parse_args(
            [
                "serve",
                "--outdir",
                str(tmp_path),
                "--api-keys-file",
                str(keys_file),
                "--api-key",
                "ignored-because-keys-file-set",
            ]
        )
        mock_app, _ = _patched_serve(monkeypatch, tmp_path, args)
        with patch("osimflow.api.create_app", return_value=mock_app) as mock_create:
            with caplog.at_level(logging.WARNING, logger="osimflow.__main__"):
                result = _cmd_serve(args)

        assert result == 0
        assert mock_create.call_args[1]["api_key"] is None
        # The pre-existing "ignored" warning must still fire.
        ignored = [
            r for r in caplog.records if "--api-key is ignored" in r.getMessage()
        ]
        assert len(ignored) == 1


class TestServeKeyGenFailure:
    """Failure path — never serve open: any key-gen error must abort serve with non-zero exit."""

    def test_key_gen_failure_aborts_with_clear_error(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        """If generate_api_key() raises, _cmd_serve exits non-zero and does not call create_app."""
        parser = _build_parser()
        args = parser.parse_args(["serve", "--outdir", str(tmp_path)])

        def _boom() -> str:
            raise RuntimeError("entropy source unavailable")

        mock_app = MagicMock()
        mock_uvicorn = MagicMock()
        monkeypatch.setitem(sys.modules, "uvicorn", mock_uvicorn)

        with (
            patch("osimflow.api.create_app", return_value=mock_app) as mock_create,
            patch("osimflow.api.generate_api_key", side_effect=_boom),
        ):
            result = _cmd_serve(args)

        # Never serve open: non-zero exit, create_app never called, uvicorn never started.
        assert result == 1
        mock_create.assert_not_called()
        mock_uvicorn.run.assert_not_called()
        captured = capsys.readouterr()
        assert "failed to auto-generate API key" in captured.err
        assert "entropy source unavailable" in captured.err
        # The instruction must guide the operator to the explicit override.
        assert "--api-key" in captured.err


class TestServeHelpText:
    """The serve --help text must mention the new auto-gen behaviour (issue #1553)."""

    def test_help_mentions_autogen(self, capsys: pytest.CaptureFixture[str]) -> None:
        parser = _build_parser()
        with pytest.raises(SystemExit) as exc_info:
            parser.parse_args(["serve", "--help"])
        assert exc_info.value.code == 0
        captured = capsys.readouterr()
        # The --api-key help text must reference the auto-gen + issue #1553.
        assert "1553" in captured.out
        assert "ephemeral" in captured.out.lower() or "auto-generat" in captured.out.lower()
